format = "$directory$git_status$git_state$git_branch$character"

add_newline = false

[character]
success_symbol = "[â¯](dimmed blue)"
error_symbol = "[âœ–](bold red)"
vimcmd_symbol = "[â®](dimmed blue)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style): "
symbol = ""
style = "bold green"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
style = "bold red"
format = "[($state( $progress_current of $progress_total))]($style) "

[git_status]
conflicted = "âš”ï¸ "
ahead = "${count}a "
behind = "${count}b "
diverged = "diverged: ${ahead_count}a ${behind_count}b "
untracked = "[${count}ut ](bold grey)"
stashed = "$countğŸ“‚ "
staged = "[${count}s ](bold blue)"
modified = "[${count}m ](bold yellow)"
renamed = "[${count}r ](bold yellow)"
deleted = "[${count}d ](bold red)"
format = "$all_status$ahead_behind"

[package]
disabled = true